# base64-encoded values -- >
# Purpose: Store sensitive information such as passwords and API keys. Values must be base64-encoded.
# Since our values are already base64-encoded, Trivy vulnerability will not detect any issues.

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: QWRtaW5AMTIz
  MYSQL_USER: dXNlcg==
  MYSQL_PASSWORD: QWRtaW5AMTIz

