# These are sensitive values.
apiVersion: v1
kind: Secret
metadata:
  name: ortho-secrets
  namespace: default
type: Opaque
data:
  # Just a small project, so not worried about keeping secrets here.
  MYSQL_PASSWORD: b3J0aG8=
  MYSQL_ROOT_PASSWORD: b3J0aG8=
  SECRET_KEY: eW91cl9mbGFza19zZWNyZXRfa2V5
  MAIL_PASSWORD: eW91cl9tYWlsX3Bhc3N3b3Jk
