apiVersion: v1
kind: Service
metadata:
  name: orthosecure-service
  labels:
    app: orthosecure-app
spec:
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050  # Only necessary if using NodePort
      protocol: TCP
  selector:
    app: orthosecure-app
  type: NodePort  # Use ClusterIP and Ingress for production