apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    app: phpmyadmin-orthosecure
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080  # Only necessary if using NodePort
      protocol: TCP
  selector:
    app: phpmyadmin-orthosecure
  type: NodePort  # Use ClusterIP and Ingress for production

  #thats all ?
  # lets see