apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restricted-deployer-binding  # Name of the RoleBinding
  namespace: secure-namespace        # Namespace of the RoleBinding
subjects:
  - kind: ServiceAccount
    name: app-service-account        # Name of the ServiceAccount
    namespace: secure-namespace
roleRef:
  kind: Role
  name: restricted-deployer         # Role being bound
  apiGroup: rbac.authorization.k8s.io
